version: '3'
services:
  postgres:
    image: postgres:14.2
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/postgres_tmp:/tmp